### ISSUE TITLE
Consider making Constants non-constant

### ISSUE THREAD

**Issue by DJDANNY123** [keycloak/keycloak-operator#102]
## Description
Constants are currently specified within /pkg/model/constants.go
These constants may not be useful for all deployments, so would there be a way of specifying/changing these at runtime/ within a ConfigMap rather than having to clone the repository and rebuild your own operator to change these.

**Comment by slaskawi** [comment]
Thanks for submitting this issue @DJDANNY123 !

Hardcoding values in `/pkg/model/constants.go` makes it much easier to maintain this code. We know exactly what kind of naming pattern will be used for our Routes, Service, Persistent Volumes and other objects. This way we can rely on it.

Allowing users to modify them in the runtime will introduce a lot of potential misconfiguration problems. We would need to carefully explain in our documentation what values could be used and what could not. It's a lot of unnecessary maintenance burden for us and we'd like to avoid it.

But before closing this issue, let me ask you what problem are you trying to solve? Perhaps we could help you in some other way?

**Comment by DJDANNY123** [comment]
Hi @slaskawi 

The particular values I am looking to specify are the images, I am currently for security reasons running a cluster disconnected from the internet, so would like to be able to deploy the operator to fetch the images from an on-premises docker repository, which is what we currently do for our deployment of the community elastic-search operator.

I assume we could do this manually by changing these values and rebuilding the operator ourselves, however it would be easier for us and maybe some others to have this feature built-in, although I understand if this would be harder to maintain.

Thanks for you help.

**Comment by abstractj** [comment]
@DJDANNY123 thanks for reporting this. I'd appreciate if you join us on the https://groups.google.com/forum/#!forum/keycloak-dev, so we can continue this discussion there.

Our [contributing guidelines](https://github.com/keycloak/keycloak-operator/blob/master/CONTRIBUTING.md) were updated to keep consistency across the Keycloak organization and soon GH issues will be disabled.

For now, I'm closing this, but feel free to drop us an e-mail on the dev mailing list if you have any questions. My apologies for the inconvenience. //cc @slaskawi
