### ISSUE TITLE
Plugin needs to expose a port on the keycloak pod

### ISSUE THREAD

**Issue by matskiv** [keycloak/keycloak-operator#107]
## Description
I was trying to use [keycloak plugin for enmasse](https://github.com/EnMasseProject/enmasse/tree/master/keycloak-plugin) and I was unable to do that because it needs to expose ports that are not exposed by keycloak pods ([5671](https://github.com/EnMasseProject/enmasse/blob/2d72fe9b4c31749fad30f55a06c0b130f8dc03b4/keycloak-plugin/sasl-plugin/src/main/java/io/enmasse/keycloak/spi/AmqpServerProviderImpl.java#L64) or [5672](https://github.com/EnMasseProject/enmasse/blob/2d72fe9b4c31749fad30f55a06c0b130f8dc03b4/keycloak-plugin/sasl-plugin/src/main/java/io/enmasse/keycloak/spi/AmqpServerProviderImpl.java#L54)).
And operator will override any changes to pod template in StatefulSet, so support for this kind of plugins would need to be added to the operator code.

What would be your thoughts on adding an optional field to "Keycloak" spec, that would define a list of additional ports that need to be exposed?
Ping @slaskawi @abstractj

**Comment by matskiv** [comment]
I created a prototype and briefly tested it. I can send a PR for this proposal, unless someone strongly against this.

**Comment by slaskawi** [comment]
@matskiv Exposing ports in the image is just a hint for other tools. It's not strictly required.

I believe you could try creating a separate Service object (in front of the Keycloak StatefulSet) that uses target port that you need. Then wire all other bits to that Service. 

Please let me know if that works.

**Comment by matskiv** [comment]
@slaskawi Oh, I didn't know that exposing was optional.
I am currently blocked by an SSL issue in a plugin (https://github.com/EnMasseProject/enmasse/issues/3551), so I can't test yet, but I will update this issue as soon as I can.
Thank you!

**Comment by abstractj** [comment]
@matskiv thanks for reporting this. I'd appreciate if you join us on the https://groups.google.com/forum/#!forum/keycloak-dev, so we can continue this discussion there.

Our contributing guidelines were updated to keep consistency across the Keycloak organization and soon GH issues will be disabled.

For now, I'm closing this, but feel free to drop us an e-mail on the dev mailing list if you have any questions. My apologies for the inconvenience. //cc @slaskawi
