### ISSUE TITLE
keycloak client using context.TODO

### ISSUE THREAD

**Issue by philbrookes** [keycloak/keycloak-operator#23]
I just noticed that the keycloak client is using `context.TODO()` and have recently learned that this is not a good, as this context can never be cancelled. For example here: https://github.com/keycloak/keycloak-operator/blob/master/pkg/common/cluster_actions.go#L52

There is an interesting article on it here:
https://www.sohamkamani.com/blog/golang/2018-06-17-golang-using-context-cancellation/

The general idea is that you pass down a context that you have a handle to the cancel on, so that any point the context can be cancelled and all in progress or further requests will be unsuccessful, this is useful if, for example, the CR has just been deleted.

You can see how we use it in the integreatly-operator, here: 
https://github.com/integr8ly/integreatly-operator/blob/master/pkg/controller/installation/installation_controller.go#L44-L55

And here:
https://github.com/integr8ly/integreatly-operator/blob/master/pkg/controller/installation/installation_controller.go#L138

@pb82 @davidffrench @sebastienblanc

**Comment by davidffrench** [comment]
Thank you @philbrookes , I have addressed this in a new PR https://github.com/keycloak/keycloak-operator/pull/24 . We do not have a use case to cancel the context just yet so this has not been added to the PR.

**Comment by davidffrench** [comment]
Issue has now been resolved in https://github.com/keycloak/keycloak-operator/pull/24
