### ISSUE TITLE
KeycloakClient secret reference

### ISSUE THREAD

**Issue by kfox1111** [keycloak/keycloak-operator#399]
### Describe the bug

The KeycloakClient object's secret field is the actual password to load, not a reference to a secret where the actual password is stored. It is considered bad practice to put secret material in any Kubernetes object other then a secret. There does not seem to be any other way to load a secret into the Keycloak Client by api other then the secret field. Some more details here: https://keycloak.discourse.group/t/keycloakclient-secret/11787. Currently no one has answered.

### Version

15.0.2

### Expected behavior

spec.secret should be a reference to a secret, or a new spec.secretRef should be added.

### Actual behavior

the secret is plantext in the CR.

**Comment by stromnet** [comment]
While upgrading RHSSO from 7.4.6 (I think, not sure. That is what we have in another cluster that is not yet upgraded 9.0.13)) to 7.5.0 (KC 15.0.2) we had problem with KeycloakClients no longer being able to authenticate. Their client secret was no longer matching.
We previously had a dummy secret value in our KeycloakClient objects, and had clicked Renegerate Secret in the UI. This was a bit manual, but kept the actual secrets out of k8s object (and git repo where it was sourced from). Previously, the dummy value was never (re-?)imported into KC, so the generated one was used, and all worked fine.

After the upgrade, the dummy value is now used, and our Clients failed to authenticate. To fix it, we had to put a "real" secret in the KeycloakClient object, as you describe.

Funny thing is, there is actually a Secret object named `keycloak-client-secret-<CLIENTID>` for each KeycloakClient object. Which the operator manages.
And looking at https://github.com/keycloak/keycloak-operator/blob/main/pkg/apis/keycloak/v1alpha1/keycloakclient_types.go#L72, that seems to be what is supposed to happen.. 

Actually, take all of the above with a grain of salt, the only thing I'm sure of is the outcome: client secrets was reverted when we upgraded, and now are reverted to whatever is in KeycloakClient object more or less immediately even if regenerated in UI (it was for sure not before).

But yes, specifying a secretRef instead would be a nice solution. Or if not set, autocreate a autogenerated secret or something.

**Comment by kfox1111** [comment]
Yeah. I've had the same experience. I'm not able to consistently keep the password what I want it to be without putting it in the actual CR.

The other option would be for it to use the generated secret's password over whats in the CR if the generated secret already exists. Then that would be the source of truth rather then the CR.

**Comment by sathieu** [comment]
Another scary thing: If you don’t specify it in the CR, it takes the name as default value 😱 .

This is not what the [linked page](https://keycloak.discourse.group/t/keycloakclient-secret/11787) tells:

> [wrong] If you don’t specify it in the CR, it seems to randomly generate a new secret. Which is not so useful for reproducibility. [/wrong]

Also related: https://github.com/keycloak/keycloak-operator/issues/411, for idp.

**Comment by vmuzikar** [comment]
@kfox1111 Thank you for reporting this. Even though this is far from ideal, it is by design from day 1. We do not plan to change this in the current operator but we'll re-evaulate how credentials and secrets in general are handled in the new operator for Keycloak.X as we're revisiting our approach around CRDs with the focus on thread modeling in general.

@stromnet This change is actually a [bug fix](https://issues.redhat.com/browse/KEYCLOAK-16102).

@sathieu OIDC IdPs can use [Keycloak Vault functionality](https://www.keycloak.org/docs/latest/server_admin/index.html#_vault-administration).
