### ISSUE TITLE
Allow setting the Resources Labels also in the reconciliation process

### ISSUE THREAD

**Issue by jonathanvila** [keycloak/keycloak-operator#404]
### Description

Now the resources labels are added after the creation of a CR ( KEYCLOAK-19405 ) but this won't cover adding them to the current existing resources after the operator upgrade.

Take into consideration keeping the rest of labels already set in the resources ( statefulset ).

**Comment by andreaTP** [comment]
At best of my understanding the solution for this issue have been already merged.
Feel free to re-open it if I missed something 🙂
