### ISSUE TITLE
Keycloak CRD should allow for customizing liveness/readiness probes

### ISSUE THREAD

**Issue by NickG22293** [keycloak/keycloak-operator#419]
### Description

Change the Keycloak CRD and associated constructs to take in parameters defining different healthcheck criteria for liveness/readiness. Could be just a change to the failureThreshold, or the initialDelaySeconds, or a redefinition of what constitutes the health checks themselves. 

### Motivation

Deploying a Keycloak instance via the operator in a resource-constrained environment can lead to Kubernetes killing and restarting the deployment due to failing liveness probes, as it takes longer for the keycloak server to actually bootstrap (I imagine CPU throttling being the underlying cause in our case). Being able to extend or modify those health checks would allow for Keycloak deployment in a wider variety of environments. 

### Details

I believe this will be a simple change to the CRD, and the const values defined in the accompanying KeycloakDeployment code in Go.

**Comment by NickG22293** [comment]
I'd be happy to start working on an implementation if this concept is considered worthy of implementing.

**Comment by andreaTP** [comment]
Hi @NickG22293 ,
I do understand that the feature you are requesting is possibly useful, although we are currently planning to completely re-write the operator:
https://github.com/keycloak/keycloak-community/pull/330

I encourage you to ask for this feature in the upcoming operator, for now I close this issue, feel free to re-open it or continue the discussion 🙂

**Comment by vmuzikar** [comment]
@NickG22293 It is actually possible to use a custom scripts for liveness and readiness checks. All you need to do is to overwrite the [default ConfigMap](https://github.com/keycloak/keycloak-operator/blob/main/pkg/model/keycloak_probes.go), the operator won't overwrite it back to its default values.

However, the thresholds etc. are [hardcoded](https://github.com/keycloak/keycloak-operator/blob/7a23cff1a2efe2856c9bf9740f9b2a52af3c0a08/pkg/model/keycloak_deployment.go#L17-L22) and unconfigurable.

**Comment by Kampe** [comment]
Please reopen and fix this.
