### ISSUE TITLE
Publish Keycloak Operator 15.1.1  in OperatorHub

### ISSUE THREAD

**Issue by jonathanvila** [keycloak/keycloak-operator#420]
### Description

Publish Keycloak Operator 15.1.1 in OperatorHub.io

### Motivation

New KC version

**Comment by jonathanvila** [comment]
PRs on Operatorhub : 
https://github.com/k8s-operatorhub/community-operators/pull/513
https://github.com/redhat-openshift-ecosystem/community-operators-prod/pull/543

**Comment by chrisguoado** [comment]
![image](https://user-images.githubusercontent.com/2968280/146570918-ffa5b58b-2315-4bbe-8d36-96d01ef808c6.png)
Well, the operator is now upgraded, but the keycloak image hasn't been built out ...

![image](https://user-images.githubusercontent.com/2968280/146571027-95e902d4-f3be-496a-879a-0f3452abd905.png)

**Comment by Nyefan** [comment]
Is there a way to force a downgrade or lock to a specific version?

**Comment by jonathanvila** [comment]
Yes you can set RELATED_IMAGE_KEYCLOAK in the Operator env vars with the
value of the 15.1.0 image.

In the operator yaml :
- name: OPERATOR_NAME
value: keycloak-operator
- name: RELATED_IMAGE_KEYCLOAK <-----------
value: 'quay.io/keycloak/keycloak:15.1.0'

**Comment by Nyefan** [comment]
@jonathanvila I have tried this several times - it is immediately reverted by the olm.

**Comment by jonathanvila** [comment]
are you changing the operator or the CR ?

**Comment by vmuzikar** [comment]
@Nyefan If using OLM, you need to modify the Subscription to set env vars on operator pod. See: https://github.com/operator-framework/operator-lifecycle-manager/blob/master/doc/design/subscription-config.md

**Comment by indiealexh** [comment]
Got an example of what the Subscription should look like? @vmuzikar @Nyefan

**Comment by jonathanvila** [comment]
@indiealexh  yes, here you have it : https://gist.github.com/jonathanvila/9efb3e8c1b7664184810fdd564fc00fa

**Comment by indiealexh** [comment]
> @indiealexh yes, here you have it : https://gist.github.com/jonathanvila/9efb3e8c1b7664184810fdd564fc00fa
@jonathanvila You are a life saver! I had animal health scans waiting for auth to come back. I suppose thats what I get for enabling automatic upgrade.

**Comment by jonathanvila** [comment]
@indiealexh glad to help , but don't copy the whole file, just only add the 2 lines ( 122, 123 )

This should not happen in the future, I will pay more attention to it.

**Comment by stianst** [comment]
15.1.1 and 16.0.0 are pushed manually for now as Quay auto builds didn't work.
