### ISSUE TITLE
Define a client with PCKE challenge method

### ISSUE THREAD

**Issue by raffopiteco** [keycloak/keycloak-operator#442]
### Description

Be able to define a client with the PCKE challenge method enabled.

### Motivation

The feature could be useful to configure clients authorization flows that are more resilient against CSRF and authorization code injection attacks.

**Comment by andreaTP** [comment]
Hi @raffopiteco ,

you should be able to configure PCKE using the `attributes` section with something like:

```yaml
attributes:
  pkce.code.challenge.method: "S256"
```

can you please double check?

As a general rule I would manually perform the configuration of a Keycloak installation, [export the configuration](https://www.keycloak.org/docs/latest/server_admin/#assembly-exporting-importing_server_administration_guide) and configure the CRD accordingly.

**Comment by mncofinpro** [comment]
@andreaTP Does work for me as you described it. Thx

**Comment by andreaTP** [comment]
Thanks for getting back @mncofinpro !
