### ISSUE TITLE
OLM MultiNamespace support

### ISSUE THREAD

**Issue by gilliangoud** [keycloak/keycloak-operator#444]
### Description

Currently while adding extra namespaces to the 'targetNamespaces' in the operatorgroup definition for keycloak an error is presented: 'installmodeset does not support operatorgroups namespace selection'.

I have not tried to run the operator on it's own yet and it seems like in cmd/manager/main.go there is support for multiple namespaces. Would it be as simple as enabling the support for deployments through OLM?

### Motivation

Deploying an additional dev/staging keycloak would be pretty nice.

**Comment by andreaTP** [comment]
Given the fact that this Operator will go [EOL soon enough](https://www.keycloak.org/2022/04/keycloak-1800-released), we do not have the bandwidth to implement this feature here.
Although I encourage you to open this very same issue for the new operator: https://github.com/keycloak/keycloak/tree/main/operator
