### ISSUE TITLE
KeycloakRealm deletion stuck on namespace deletion

### ISSUE THREAD

**Issue by Arcahub** [keycloak/keycloak-operator#446]
### Describe the bug

When i delete a namespace that have a keycloak instance and a keycloak realm custom resource managed by the keycloak operator, the namespace get stuck in terminating state and it seems that it came from the keycloakRealm resource deletions

### Version

I let olm manage the operator version so i should be the latest available on olm

### Expected behavior

The keycloakRealm resource should be deleted when the namespace ask for it

### Actual behavior

The keycloakRealm resource won't be deleted and block the deletions of the namespace

### How to Reproduce?

Start a k8s cluster
Install OLM operator
Install Keycloak Operator
Create a Keycloak Instance in the namespace watched by the operator
Create a Keycloak Realm in the the namespace watched by the operator with a selector corresponding to the keycloak instance previously created
Check that both the keycloak instance and the realm are working
Delete the namespace containing the resources  
You should the the namespace stuck in the terminating status and you won't be able to manually delete the realm

### Anything else?

When i first delete the realm then delete the namespace it's working well. I think it's might be because the instance got deleted before the realm and then the realm can't delete itself from the non existing instance

**Comment by andreaTP** [comment]
Hi @Arcahub ,
thanks for opening this issue, can I ask you to provide the output of:

```bash
kubectl get namespace <namespace-stuck> -o yaml
```

I'm especially interested in the `.spec.finalizers` section to understand which resource is blocking the deletion process.
Thanks in advance!

**Comment by Arcahub** [comment]
Hi @andreaTP,
Here is the log you asked for the terminating namespace:
```apiVersion: v1
kind: Namespace
metadata:
  creationTimestamp: "2022-01-22T14:09:25Z"
  deletionTimestamp: "2022-01-22T14:39:21Z"
  labels:
    istio-injection: enabled
    kubernetes.io/metadata.name: dev-station-sso
  name: dev-station-sso
  resourceVersion: "6878"
  uid: 2e3f83cd-bbd5-484f-b73d-d72f2aee40c1
spec:
  finalizers:
  - kubernetes
status:
  conditions:
  - lastTransitionTime: "2022-01-22T14:39:32Z"
    message: All resources successfully discovered
    reason: ResourcesDiscovered
    status: "False"
    type: NamespaceDeletionDiscoveryFailure
  - lastTransitionTime: "2022-01-22T14:39:32Z"
    message: All legacy kube types successfully parsed
    reason: ParsedGroupVersions
    status: "False"
    type: NamespaceDeletionGroupVersionParsingFailure
  - lastTransitionTime: "2022-01-22T14:39:32Z"
    message: All content successfully deleted, may be waiting on finalization
    reason: ContentDeleted
    status: "False"
    type: NamespaceDeletionContentFailure
  - lastTransitionTime: "2022-01-22T14:39:32Z"
    message: 'Some resources are remaining: keycloakrealms.keycloak.org has 1 resource
      instances'
    reason: SomeResourcesRemain
    status: "True"
    type: NamespaceContentRemaining
  - lastTransitionTime: "2022-01-22T14:39:32Z"
    message: 'Some content in the namespace has finalizers remaining: realm.cleanup
      in 1 resource instances'
    reason: SomeFinalizersRemain
    status: "True"
    type: NamespaceFinalizersRemaining
  phase: Terminating```

**Comment by andreaTP** [comment]
Looks like the Realm CR is getting stuck on finalizers, I believe that if you delete first the Keycloak Realm CR, wait for it to be completely gone and try to delete the namespace everything should flow as expected.

**Comment by Arcahub** [comment]
Sorry for the late answer. Yeah as you said if i first delete the realm and the delete the namespace everything is fine but i think the real problem is that when a keycloak instance is deleted the linked ressources like realm aren't deleted. I think this should be the default behavior

**Comment by andreaTP** [comment]
Hi @Arcahub ,
it's a pretty common practice for operators to set finalizers on CRs to prevent them to be accidentally removed.
In this case, the Keycloak CR is not aware of the fact that a Realm CR exists, while the Realm CR references Keycloak instances by matching labels, and they can be re-created at any point in time; so, the current behaviour is "safe" to prevent not intended removal of CRs.

**Comment by Arcahub** [comment]
Ok I understand the wanted behaviour. Thanks for the support, I will close this issue.
