### ISSUE TITLE
Error creating a user in different namespace than his realm

### ISSUE THREAD

**Issue by christianviana** [keycloak/keycloak-operator#455]
### Describe the bug

When creating a user in a different namespace than his realm, user is not properly created

### Version

16.1.0

### Expected behavior

User created properly, with error messages at keycloak's console neither operator's console, and without the reported side-effects

### Actual behavior

User is being created and can ben seen at web console, but according to the logs there are some problems with the creation and there are also some side-effects

Message logs:

```
0)    SUCCESS check if keycloak is available"}
1)    SUCCESS update user test1-christian"}
2)     FAILED create credential secret for user test1-christian in realm default/basic-realm : "cross-namespace owner references are disallowed, owner's namespace namespace2, obj's namespace namespace1"
```
Side-effects:

- if we try to delete the resource using kubectl delete, the CR gets deleted, but the user remains in keycloak
- if we try to recreate the same user afterwards, it results in a "409 conflit", because the user will be still in the keycloak database

We are suspecting that this error is because the operator is trying to create the user's secret in another namespace, which is not allowed by kubernetes.

### How to Reproduce?

- Install the operator having the variable WATCH_NAMESPACE set to ""
- Create a basic-realm from the operator's docs in a namespace called, for example, namespace1
- Create a user in another namespace, for example, namespace2
- This will result in message logs:

```
0)    SUCCESS check if keycloak is available"}
1)    SUCCESS update user test1-christian"}
2)     FAILED create credential secret for user test1-christian in realm default/basic-realm : "cross-namespace owner references are disallowed, owner's namespace namespace2, obj's namespace namespace1"
```
- Afterwards, if we try to delete the resource using kubectl delete, the CR gets deleted, but the user remains in keycloak
- if we try to recreate the same user afterwards, it results in a "409 conflit", because the user will be still in the keycloak database

### Anything else?

- We need to test this in an environment that has the operator deployed with the variable WATCH_NAMESPACE set to "", so it can watch over all namespaces in the cluster.
- If this is confirmed as a bug, is there any workaround you can think of, like for example: there is a way to provide our own created secret to the user so it don't has to be created by the operator?

**Comment by stianst** [comment]
Thanks (again) for reporting this issue. Keycloak 19 was the last version that included this legacy Operator, and with the release of Keycloak 20 the Operator reached EOL and this repository will be archived, please see our [blog post](https://www.keycloak.org/2022/03/releases.html) on this topic. If this issue is still valid for the [Realm Operator](https://github.com/keycloak/keycloak-realm-operator), please re-open it there. Thanks for your understanding. And be sure to check out our [new Operator](https://www.keycloak.org/guides#operator)!
