### ISSUE TITLE
Update legacy image coordinates in the image manager

### ISSUE THREAD

**Issue by vmuzikar** [keycloak/keycloak-operator#463]
### Description

With KC 17, Quarkus is becoming the default distribution. That means the WF dist will have the image coordinates changed and the operator needs to reflect that (the operator supports only the WF dist).

**Comment by benlangfeld** [comment]
Will the operator be upgraded to support the Quarkus version?

**Comment by vmuzikar** [comment]
@benlangfeld This operator will be deprecated together with the deprecation of WildFly distribution some time in the future. For the Quarkus distribution we're developing a new operator (that's also based on Quarkus). Feel free to share your thoughts on the [design proposal](https://github.com/keycloak/keycloak-community/pull/330)!
