### ISSUE TITLE
Update legacy image coordinates in `set-version.sh`

### ISSUE THREAD

**Issue by vmuzikar** [keycloak/keycloak-operator#464]
### Description

With KC 17, Quarkus is becoming the default distribution. That means the WF dist will have the image coordinates changed and the operator needs to reflect that (the operator supports only the WF dist).

**Comment by rucelee** [comment]
Hi,
will the operator support Quarkus Keycloak any time soon?

**Comment by vmuzikar** [comment]
@rucelee Hello, thank you for your interest in Keycloak and the operator. This operator won't support the Quarkus distribution and will be deprecated together with the WildFly distribution in the future. For Quarkus dist, we're developing a [new operator](https://github.com/keycloak/keycloak/tree/main/operator) which should be [released as part of KC 18](https://www.keycloak.org/2022/03/releases) as a tech preview.

Plese notice that this is not the right place to ask questions. I'd like to ask if you could open a [question on GitHub](https://github.com/keycloak/keycloak/discussions/categories/q-a) for future inquiries. Thank you.

**Comment by rucelee** [comment]
@vmuzikar Thank you indeed for a detailed response. I'll bring the further questions to [question on GitHub](https://github.com/keycloak/keycloak/discussions/categories/q-a)
