### ISSUE TITLE
Secret generated by explicitly defining a client secret in KeycloakClient CRD is not named as it is documented

### ISSUE THREAD

**Issue by CreamyMiracle** [keycloak/keycloak-operator#473]
### Describe the bug

In the documentation (https://www.keycloak.org/docs/latest/server_installation/index.html#_client-cr) it is stated that: "After a client is created, the Operator creates a Secret containing the Client ID and the client’s secret using the following naming pattern: `keycloak-client-secret-<custom resource name>`". However, the secret appears not to be named after CRD name itself but rather after the "clientId" field set for the client defined in the CRD. This causes problems when deploying clients with the same id in different realms, since Operator apparently tries to create one secret per each client but the secret names aren't unique due to the secret naming pattern (`keycloak-client-secret-<clientId>`).

### Version

16.1.0

### Expected behavior

Operator should name the created client secret with respect to pattern `keycloak-client-secret-<custom resource name>`

### Actual behavior

Operator names the created client secret with respect to pattern `keycloak-client-secret-<clientId>`

### How to Reproduce?

1. Deploy Keycloak Operator
2. Deploy a realm
3. Deploy a client to this realm with the following CRD 
 
`apiVersion: keycloak.org/v1alpha1
kind: KeycloakClient
metadata:
  name: someName
  labels:
    app: app=example-keycloak
spec:
  realmSelector:
     matchLabels:
      app: <matching labels for KeycloakRealm custom resource>
  client:
    clientId: someClientId
    secret: thisisasecret`

4. Check the secret to confirm it was named "keycloak-client-secret-someClientId" rather than "keycloak-client-secret-someName"

**Comment by trevorloranger** [comment]
Hi @CreamyMiracle, just FYI I was working on this and opened a PR to resolve this issue (which we also have encountered recently). Thanks!

**Comment by andreaTP** [comment]
Hi @CreamyMiracle ,
as I understand this issue, it would require to fix the docs on this page:
https://github.com/keycloak/keycloak-documentation/blob/21d73659caa9b2356f15bd253a9078a922cfb159/server_installation/topics/operator/keycloak-client-cr.adoc

@trevorloranger any specific context I'm missing for changing the code instead of the documentation?

**Comment by CreamyMiracle** [comment]
Hi @andreaTP ,
Yes, that piece of documentation is the one that I was referring to. I prefer changing the code instead of documentation, because currently you can't deploy two or more clients with the same client id in different realms, since all of those KeycloakClient CRD's would create a secret with exactly same name _keycloak-client-secret-<clientId>_ and this causes problems since Kubernetes (obviously) want's secrets to have unique names.

**Comment by trevorloranger** [comment]
@andreaTP see @CreamyMiracle post above but in summary using the custom resource name for secrets will guarantee uniqueness (since CR name must be unique within a k8s namespace) and allow for our multi-realm scenarios where we have same clientID being used in multiple realms.

**Comment by andreaTP** [comment]
Thanks for additional context! I'll follow up in the PR.
