### ISSUE TITLE
Keycloak Operator does not work with Data Backups

### ISSUE THREAD

**Issue by apeschel** [keycloak/keycloak-operator#476]
### Describe the bug

The keycloak-operator will only reconcile and manage keycloak resources that it created itself. It will throw an error if it is configured to manage keycloak resources that already exist.

Errors like this show up in the log:

```
{"level":"info","ts":1644259394.2589386,"logger":"action_runner","msg":"(    1)     FAILED create client foo/bar : failed to create client: (409) 409 Conflict"}
```

For us, this is most likely to happen when the keycloak database is restored from a backup, but here's a longer list of scenarios that it applies to:

* Restoring the database from a backup
* The keycloak operator is removed and reinstalled on a cluster.
* A keycloak resource is removed an recreated on a cluster.

### Version

16.1.0

### Expected behavior

The keycloak operator should be able to manage state for existing resources that it didn't create itself. A logic flow like this would be good:

1. If a resource already exists, load in the metadata and configs for that existing resource from the keycloak service, and treat it no differently than if the keycloak-operator had created it.
2. If a resource doesn't exist in the keycloak deployment, create and manage it.
3. Enter the standard reconcile loop regardless of where the resource originally was created.

### Actual behavior

Keycloak-operator refuses to reconcile and manage any resource it did not directly create itself, with this specific instance of the keycloak-operator.

### How to Reproduce?

1. Create a keycloak resource backed by a persistent database. Create some additional keycloak resources, like a keycloakclient.
1. Take a backup of the database.
1. Make a copy of the credential-keycloak secret
1. Delete all the keycloak resources.
1. Restore the database from the backup.
2. Recreate all the keycloak resources.
3. Replace credential-keycloak with the previous copy.
4. Check the keycloak-operator logs. It will be able to connect to the keycloak service, but will complain about existing resources.

**Comment by apeschel** [comment]
There doesn't seem to be any good and supported workflow for restoring from a backup with the keycloak-operator at the moment.

The operator will also clobber the credentials-keycloak secret, which will need to be manually restored to the previous version.

Perhaps if there was some way to flag a keycloak cluster as being backed by existing data to fix some of these issues?

**Comment by apeschel** [comment]
Deleting the offending resources works and letting the keycloak-operator recreate them kind of works - except that it's very tedious, and you will lose anything that has been configured outside the operator (eg through the UI).

**Comment by andreaTP** [comment]
Hi @apeschel ,

I appreciate your interest in the Keycloak operator, I understand that this issue would be resolved if the operator supports some kind of sync back of resources, which, unfortunately it doesn't as mentioned in the official documentation:

https://www.keycloak.org/docs/15.0/server_installation/#_realm-cr

**Comment by apeschel** [comment]
@andreaTP That's a fair point, but the issue remains that the operator will continue retrying to create these resources forever, and produce a lot of errors while it's doing so.

It feels like the user story of restoring Keycloak from a backup has not been taking into account with the Keycloak Operator.

**Comment by AndersBennedsgaard** [comment]
@andreaTP what is the status of this?

In my use-case, we use Flux as a GitOps operator, and unfortunately we had to move the operator release to a new location in out Git repository. That effectively means a reinstallation of the operator - something that would be possible with most other operators. 

With the keycloak-operator, we had to manually scale down the operator and delete the custom resources (`KeyCloak`, `KeyCloakClient`, etc.) in a non-cascading manner since `ownerReferences` is used for many resources. After having moved the CRDs, scaled up the operator, and reapplied the CRs, the `KeyCloakClient` and `KeyCloakUsers` continue to complain about `failed to create client: (409) 409 Conflict` and `failed to create user: (409) 409 Conflict`. 
The `KeyCloak` and `KeyCloakRealm` resources seems to work as expected, with only a single `failed to get the admin credentials: resource name may not be empty` warning from the realms.

@apeschel's suggestion about checking if a resource already exists before continuing with the normal reconciliation loop, should do the trick.

**Comment by andreaTP** [comment]
Given the fact that this operator will [go EOL](https://www.keycloak.org/2022/04/keycloak-1800-released) soon enough, and the complexity of tackling this issue, we won't have bandwidth to do it if it's not driven by a community contribution.

For reference, the new Keycloak Operator has a [Realm Import CRD](https://www.keycloak.org/operator/realm-import) that should fill this use-case.

Tentatively closing this issue.

**Comment by brunomedeirosdedalus** [comment]
I have face the same issue. A quick workaround is to add to the client CR the 'id' field under spec.client with the 'id' of the client with problems.

Have automatized the process via script. Without having had a detailed look into the Keycloak Operator code, I am wondering if in case of duplicated client, the Operator could just add the ID into the CR and just handle that client as it has been created by the Operator itself.
