### ISSUE TITLE
Publish Keycloak-Operator 17.0.0 on operatorhub and OCP marketplace

### ISSUE THREAD

**Issue by jonathanvila** [keycloak/keycloak-operator#486]
### Description

Do the changes on this repository and the operator-framework in order to publish the operator 17.0.0

**Comment by jonathanvila** [comment]
Operatorhub PR : https://github.com/k8s-operatorhub/community-operators/pull/757

**Comment by jonathanvila** [comment]
Openshift marketplace PR : https://github.com/redhat-openshift-ecosystem/community-operators-prod/pull/807

**Comment by mbarbero** [comment]
Please have a look at #489, as this may have introduced a regression
