### ISSUE TITLE
Keycloak operator service name (hostname) change 

### ISSUE THREAD

**Issue by rakeshreddyrg09** [keycloak/keycloak-operator#495]
### Describe the bug

Hello Everyone,
I am using keycloak operator, here I am not able to find how I can pass custom service name (hostname).
When I apply keycloak manifest its creating the service as below shown
here is my keycloak manifest

> apiVersion: keycloak.org/v1alpha1
kind: Keycloak
metadata:
 labels:
     app: example-keycloak
 name: example-keycloak
 namespace: demo
spec:
 externalDatabase:
   enabled: true
 instances: 1
 externalAccess:
   enabled: True
 keycloakDeploymentSpec:
   experimental:
     env:
       - name: DB_DATABASE
         valueFrom:
           secretKeyRef:
             name: keycloak-pguser-keycloakuser
             key: dbname
       - name: DB_ADDR
         valueFrom:
           secretKeyRef:
             name: keycloak-pguser-keycloakuser
             key: host
       - name: DB_PORT
         valueFrom:
           secretKeyRef:
             name: keycloak-pguser-keycloakuser
             key: port
       - name: DB_PASSWORD
         valueFrom:
           secretKeyRef:
             name: keycloak-pguser-keycloakuser
             key: password
       - name: DB_USER
         valueFrom:
           secretKeyRef:
             name: keycloak-pguser-keycloakuser
             key: user

here is the service which is created by keycloak

  > apiVersion: v1
  kind: Service
  metadata:
    name: keycloak-discovery
    namespace: test
    uid
    resourceVersion: '12345'
    creationTimestamp: '2022-02-22T06:32:44Z'
    labels:
      app: keycloak
    ownerReferences:
      - apiVersion: keycloak.org/v1alpha1
        kind: Keycloak
        name: demo-keycloak
        uid: 
        controller: true
        blockOwnerDeletion: true
    managedFields:
      - manager: keycloak-operator
        operation: Update
        apiVersion: v1
        time: '2022-02-22T06:32:44Z'
        fieldsType: FieldsV1
    selfLink: /api/v1/namespaces/test/services/keycloak-discovery
  status:
    loadBalancer: {}
  spec:
    ports:
      - protocol: TCP
        port: 8080
        targetPort: 8080
    selector:
      app: keycloak
      component: keycloak
    clusterIP: None

can anyone help how I can have control over creating this service.

Thank you.

### Version

16.1.0

**Comment by andreaTP** [comment]
Hi @rakeshreddyrg09 ,

thanks for reaching out, currently, the service name is constant and cannot be modified by users, ref:
https://github.com/keycloak/keycloak-operator/blob/77d126113104d45e29057f5c9e30c54f1a482763/pkg/model/constants.go#L17

Would you mind to elaborate on. the reasons why you would need to change it? Thanks in advance!

**Comment by rakeshreddyrg09** [comment]
we found the work around for this. Thank you.
