### ISSUE TITLE
re: keycloak CRD - add the capability so keycloak exposes itself on a HTTP port

### ISSUE THREAD

**Issue by alf5** [keycloak/keycloak-operator#517]
### Description

Be able to get the Keycloak pod to expose itself over HTTP

### Discussion

Add something in the keycloak CRD so Keycloak exposes itself on a HTTP port.

### Motivation

TLS is terminated by the ingress controller
Useful for the ingress controllers that don't or can't talk HTTPS to backends

### Details

e.g. launch the keycloak pod with env vars set to:
KC_HTTP_ENABLE="true"
KC_HTTP_PORT="8080"

ref: https://www.keycloak.org/server/all-config

**Comment by albertot** [comment]
There is any workaround for this.  We are running behind istio and we need to connect to port 8080.

**Comment by vmuzikar** [comment]
Hi @alf5 and  @albertot! Unfortunately, the old operator doesn't support HTTP and we do not plan to add it. Please note that the reference link you provided is for the Quarkus distribution of Keycloak. The old operator supports only WildFly distribution.

However, we are developing a [new operator](https://github.com/keycloak/keycloak/tree/main/operator) for the Quarkus distribution. This operator will support HTTP in some specific cases (proxy etc.) and first tech-preview will be released with [Keycloak 18](https://www.keycloak.org/2022/03/releases).
