### ISSUE TITLE
Add possibility to customize the Ingress resource created for the `Keycloak` CRD

### ISSUE THREAD

**Issue by matheushent** [keycloak/keycloak-operator#520]
### Description

Currently the operator creates an Ingress resource ([source code](https://github.com/keycloak/keycloak-operator/blob/main/pkg/model/keycloak_ingress.go#L18-L59)) during the deployment of the `Keycloak` CRD. I think it makes sense to enable the customization of the annotations before deployment time because not all scenarios will use the nginx controller (as the code supposes).

### Motivation

A "default" Ingress resource is created when deploying any `Ingress` resource but this resource doesn't fit any general use case. My motivation came when I needed to deploy a totally separated Ingress resource to fit my use case (AWS deployment goals) and then I had two Ingress resources for the same purpose but one of them fit the goal.

### Details

For implementation ideas I propose to let the person who is deploying to input the ingress annotations. In case no input comes, then the operator deploys the current implementation (nginx annotations).

**Comment by andreaTP** [comment]
Hi @matheushent ,
the provided "default" ingress is NOT designed to be generic and customizable, as you already noted.

We do encourage you to disable it (`externalAccess.enabled: False`) and provide your custom ingress instead (as you have already done 🙂  ).

Let me know if you have any blocking issues with this proposal.

**Comment by matheushent** [comment]
> Hi @matheushent ,
> 
> the provided "default" ingress is NOT designed to be generic and customizable, as you already noted.
> 
> 
> 
> We do encourage you to disable it (`externalAccess.enabled: False`) and provide your custom ingress instead (as you have already done 🙂  ).
> 
> 
> 
> Let me know if you have any blocking issues with this proposal.

No problem with your idea, I just wish the documentation to be clearer about the option `externalAccess.enabled`, I mean, what it creates or not in case is disabled.

Anyway, thank you for the response.
