### ISSUE TITLE
Always create built-in authentication flows

### ISSUE THREAD

**Issue by SmithJosh** [keycloak/keycloak-operator#525]
### Description

When creating a KeycloakRealm resource, if no authentication flows are specified, the operator will create a realm with a handful of built-in flows. However, if I add a custom authentication flow, suddenly Keycloak starts complaining that the built-in flows don't exist. It appears the operator expects you to manage ALL flows if you want to customize any, which ends up being a lot of unnecessary configuration. Here's the minimal set of flows I need to provide to do any customization:

<details>
  <summary>
    Expand
  </summary>
<pre>
authenticationFlows:
  # BUILT-IN FLOWS
  - alias: browser
    description: browser based authentication
    providerId: basic-flow
    topLevel: true
    builtIn: true
    authenticationExecutions:
      - authenticator: auth-cookie
        authenticatorFlow: false
        requirement: ALTERNATIVE
        priority: 10
        userSetupAllowed: false
      - authenticator: auth-spnego
        authenticatorFlow: false
        requirement: DISABLED
        priority: 20
        userSetupAllowed: false
      - authenticator: identity-provider-redirector
        authenticatorFlow: false
        requirement: ALTERNATIVE
        priority: 25
        userSetupAllowed: false
      - authenticatorFlow: true
        requirement: REQUIRED
        priority: 30
        flowAlias: forms
        userSetupAllowed: false
  - alias: registration
    description: registration flow
    providerId: basic-flow
    topLevel: true
    builtIn: true
    authenticationExecutions:
      - authenticator: registration-page-form
        authenticatorFlow: true
        requirement: REQUIRED
        priority: 10
        flowAlias: registration form
        userSetupAllowed: false
  - alias: direct grant
    description: OpenID Connect Resource Owner Grant
    providerId: basic-flow
    topLevel: true
    builtIn: true
    authenticationExecutions:
      - authenticator: direct-grant-validate-username
        authenticatorFlow: false
        requirement: REQUIRED
        priority: 10
        userSetupAllowed: false
      - authenticator: direct-grant-validate-password
        authenticatorFlow: false
        requirement: REQUIRED
        priority: 20
        userSetupAllowed: false
      - authenticatorFlow: true
        requirement: CONDITIONAL
        priority: 30
        flowAlias: Direct Grant - Conditional OTP
        userSetupAllowed: false
  - alias: reset credentials
    description: Reset credentials for a user if they forgot their password or something
    providerId: basic-flow
    topLevel: true
    builtIn: true
    authenticationExecutions:
      - authenticator: reset-credentials-choose-user
        authenticatorFlow: false
        requirement: REQUIRED
        priority: 10
        userSetupAllowed: false
      - authenticator: reset-credential-email
        authenticatorFlow: false
        requirement: REQUIRED
        priority: 20
        userSetupAllowed: false
      - authenticator: reset-password
        authenticatorFlow: false
        requirement: REQUIRED
        priority: 30
        userSetupAllowed: false
      - authenticatorFlow: true
        requirement: CONDITIONAL
        priority: 40
        flowAlias: Reset - Conditional OTP
        userSetupAllowed: false
  - alias: clients
    description: Base authentication for clients
    providerId: client-flow
    topLevel: true
    builtIn: true
    authenticationExecutions:
      - authenticator: client-secret
        authenticatorFlow: false
        requirement: ALTERNATIVE
        priority: 10
        userSetupAllowed: false
      - authenticator: client-jwt
        authenticatorFlow: false
        requirement: ALTERNATIVE
        priority: 20
        userSetupAllowed: false
      - authenticator: client-secret-jwt
        authenticatorFlow: false
        requirement: ALTERNATIVE
        priority: 30
        userSetupAllowed: false
      - authenticator: client-x509
        authenticatorFlow: false
        requirement: ALTERNATIVE
        priority: 40
        userSetupAllowed: false
  - alias: forms
    description: Username, password, otp and other auth forms.
    providerId: basic-flow
    topLevel: false
    builtIn: true
    authenticationExecutions:
      - authenticator: auth-username-password-form
        authenticatorFlow: false
        requirement: REQUIRED
        priority: 10
        userSetupAllowed: false
      - authenticatorFlow: true
        requirement: CONDITIONAL
        priority: 20
        flowAlias: Browser - Conditional OTP
        userSetupAllowed: false
  - alias: registration form
    description: registration form
    providerId: form-flow
    topLevel: false
    builtIn: true
    authenticationExecutions:
      - authenticator: registration-user-creation
        authenticatorFlow: false
        requirement: REQUIRED
        priority: 20
        userSetupAllowed: false
      - authenticator: registration-profile-action
        authenticatorFlow: false
        requirement: REQUIRED
        priority: 40
        userSetupAllowed: false
      - authenticator: registration-password-action
        authenticatorFlow: false
        requirement: REQUIRED
        priority: 50
        userSetupAllowed: false
      - authenticator: registration-recaptcha-action
        authenticatorFlow: false
        requirement: DISABLED
        priority: 60
        userSetupAllowed: false
  - alias: Direct Grant - Conditional OTP
    description: Flow to determine if the OTP is required for the authentication
    providerId: basic-flow
    topLevel: false
    builtIn: true
    authenticationExecutions:
      - authenticator: conditional-user-configured
        authenticatorFlow: false
        requirement: REQUIRED
        priority: 10
        userSetupAllowed: false
      - authenticator: direct-grant-validate-otp
        authenticatorFlow: false
        requirement: REQUIRED
        priority: 20
        userSetupAllowed: false
  - alias: Reset - Conditional OTP
    description: Flow to determine if the OTP should be reset or not. Set to REQUIRED to force.
    providerId: basic-flow
    topLevel: false
    builtIn: true
    authenticationExecutions:
      - authenticator: conditional-user-configured
        authenticatorFlow: false
        requirement: REQUIRED
        priority: 10
        userSetupAllowed: false
      - authenticator: reset-otp
        authenticatorFlow: false
        requirement: REQUIRED
        priority: 20
        userSetupAllowed: false
  - alias: Browser - Conditional OTP
    description: Flow to determine if the OTP is required for the authentication
    providerId: basic-flow
    topLevel: false
    builtIn: true
    authenticationExecutions:
      - authenticator: conditional-user-configured
        authenticatorFlow: false
        requirement: REQUIRED
        priority: 10
        userSetupAllowed: false
      - authenticator: auth-otp-form
        authenticatorFlow: false
        requirement: REQUIRED
        priority: 20
        userSetupAllowed: false
</pre>
</details>

It would be much simpler and less error prone if the operator created those authentication flows by default. Also, these are supposed to be "builtin" flows which makes the current behavior even more surprising.

**Comment by andreaTP** [comment]
Hi @SmithJosh !
Thanks for your interest, and sorry for the late reply.

In this specific case, the operator is not behaving any differently than any REST admin Client on plain Keycloak.

I would invite you to create a matching issue on the `keycloak/keycloak` repository as this is not strictly related to operator as far as I understand it.

Let me know if there is a compelling reason to keep this issue open solely for the operator.
