### ISSUE TITLE
Deprecate `podDisruptionBudget`

### ISSUE THREAD

**Issue by vmuzikar** [keycloak/keycloak-operator#551]
### Description

* Make sure the Operator ignores the `podDisruptionBudget` field when running on K8s >=1.25.
* Deprecate the `podDisruptionBudget` field in the docs.

### Motivation

K8s 1.25 is removing some APIs. One of them is [PodDisruptionBudget v1beta1](https://kubernetes.io/docs/reference/using-api/deprecation-guide/#poddisruptionbudget-v125) that is [used](https://github.com/keycloak/keycloak-operator/blob/e99da8a15034acd1fef1fdf2e43d99efe81914f3/pkg/model/pod_disruption_budget.go) by the Operator.

**Comment by kfox1111** [comment]
I don't understand. They are removing a beta api, but because they have a v1 now. This shouldn't remove pdb support, but instead update it to use the v1 api?

**Comment by vmuzikar** [comment]
@kfox1111 Yes, that is correct. However, due to various technical reasons (which one of them is that the Operator is deprecated in the upstream) we decided drop the PDB support on newer K8s clusters.
