### ISSUE TITLE
How to enaple http by default?

### ISSUE THREAD

**Issue by ADiTuri** [keycloak/keycloak-operator#559]
### Describe the bug

I have deployed the operator on k8s and redirected the discovery-service to a public ip for testing purposes.
When I am trying to log in to the UI this message appears:

![Screen Shot 2022-06-27 at 11 38 07](https://user-images.githubusercontent.com/84565808/175909695-50b10dcd-969e-430b-a65a-ed708ed16ece.png)

I saw that in the v2 version of the CRD an option is there to [disable http](https://www.keycloak.org/operator/advanced-configuration#_disabling_required_cr_fields).

Is there an easy way to bypass this problem and use the keycloak with http for testing purposes?

### Version

v.18.0.1

**Comment by andreaTP** [comment]
@ADiTuri are you using the Quarkus or WildFly distribution?

For Quarkus you can start with `start-dev` command, for WildFly you need to follow this documentation: https://www.keycloak.org/docs/16.1/server_installation/

**Comment by ADiTuri** [comment]
I am using the operator refered in operatorhub I guess that is the WildFly one right? Does the operator do the installation automatically?
