### ISSUE TITLE
Include ARM64 in release

### ISSUE THREAD

**Issue by stevefan1999-personal** [keycloak/keycloak-operator#571]
### Description

Allow pure ARM64 Kubernetes user to run the operator in ARM64.

### Motivation

I'm running Keycloak on Oracle Cloud, using their ARM64 Altra machine type. However, there doesn't seems like to have an ARM64 build in quay.io. 

### Details

Judging from https://github.com/quarkusio/quarkus-images/issues/83 it seems like Quarkus already supported multi-arch, but building an image for it can be a little gimmicky.

**Comment by stevefan1999-personal** [comment]
Closed for wrong repo -- It seems like this repo is kept for legacy purposes. Please mark this repo as read-only, at least let people know

**Comment by patlachance** [comment]
@stevefan1999-personal if this repo is for legacy purposes, what's the new repo?

**Comment by stevefan1999-personal** [comment]
@patlachance https://github.com/keycloak/keycloak/tree/main/operator
