### ISSUE TITLE
Context root for external Keycloak instances

### ISSUE THREAD

**Issue by vmuzikar** [keycloak/keycloak-operator#572]
### Description

This is a preparation for https://github.com/keycloak/keycloak/issues/13282.

Quarkus dist by default doesn't use the `/auth` context root.

**Comment by abstractj** [comment]
@vmuzikar out of curiosity. Is the plan to keep some feature parity between the legacy Keycloak Operator and the new Keycloak Operator? I just wonder if introducing new features, means more maintenance in both projects.
