### ISSUE TITLE
CRDs can't be deployed on k8s/OCP 3.11

### ISSUE THREAD

**Issue by jairojunior** [keycloak/keycloak-operator#59]
## Description

The validation error is `must only have "properties", "required" or "description" at the root if the status subresource is enabled`

I found the same problem in this issue: https://github.com/knative/eventing-contrib/issues/114

To fix we would have to do something like this: https://github.com/knative/eventing-contrib/pull/115/files

## Environment
OpenShift 3.11

## Steps to reproduce
Deploy CRD's to an existing OCP 3.11 environment

**Comment by slaskawi** [comment]
This has been fixed in https://github.com/keycloak/keycloak-operator/pull/61
