### ISSUE TITLE
COPY failed: stat /var/lib/docker/tmp/docker-builderxxxxxxxxx/tools: no such file or directory

### ISSUE THREAD

**Issue by JiyeYu** [keycloak/keycloak-operator#90]
Hi, I am trying to create local keycloak operator image by command `operator-sdk build <image>`
However, I meet such following error. Any advice is helpful!

(seems there is no .dockerignore file in this folder)

## Description
Step 9/15 : COPY tools /opt/jboss/tools FAILs when build operator image
COPY failed: stat /var/lib/docker/tmp/docker-builderxxxxxxxxx/tools: no such file or directory

## Expected Behavior
succeed to build operator image

## Actual Behavior
Step 9/15 : COPY tools /opt/jboss/tools
COPY failed: stat /var/lib/docker/tmp/docker-builder896005541/tools: no such file or directory
Error: failed to output build image xxxxxxx/operator-hub/official-keycloak-operator: (failed to exec []string{"docker", "build", "-f", "build/Dockerfile", "-t", "xxxxxxx/operator-hub/official-keycloak-operator", "."}: exit status 1)

## Environment
* OpenShift or Kubernetes version:
oc v3.11.0+0cbc58b
kubernetes v1.11.0+d4cacc0
features: Basic-Auth GSSAPI Kerberos SPNEGO

Server https://127.0.0.1:8443
kubernetes v1.11.0+d4cacc0
* Project Version/Tag: (E.g release-1.0.1)

## Steps to reproduce
operator-sdk build xxxxxxxx/operator-hub/official-keycloak-operator

**Comment by JiyeYu** [comment]
I checked build/Dockerfiles and found the possible errors.
In build/Dockerfiles, line 21/24, which are doing the COPY job, the path is not correct.
They should be 
`COPY build/tools /opt/jboss/tools` and
`COPY build/bin /usr/local/bin`
After these two changes, I passed the image build.

**Comment by JiyeYu** [comment]
I found this commit: https://github.com/keycloak/keycloak-operator/commit/940e73d0deb492013d8bfd79f7a17c1a7e17ee33

In this commit, copy directory is changed from `build/bin` to `bin` on purpose.
Seems you are doing the `docker build` in build folder? Not by `operator-sdk build` from the root directory of this project.

Then in readme.md, https://github.com/keycloak/keycloak-operator#alternative-step-3-deploying-to-a-cluster, step:
`build image with operator-sdk build <image registry>/<organisation>/keycloak-operator:<tag>. e.g. operator-sdk build quay.io/keycloak/keycloak-operator:test` would be failed as this issue shows. 🤔

**Comment by abstractj** [comment]
> I found this commit: [940e73d](https://github.com/keycloak/keycloak-operator/commit/940e73d0deb492013d8bfd79f7a17c1a7e17ee33)
> 
> In this commit, copy directory is changed from `build/bin` to `bin` on purpose.
> Seems you are doing the `docker build` in build folder? Not by `operator-sdk build` from the root directory of this project.
> 
> Then in readme.md, https://github.com/keycloak/keycloak-operator#alternative-step-3-deploying-to-a-cluster, step:
> `build image with operator-sdk build <image registry>/<organisation>/keycloak-operator:<tag>. e.g. operator-sdk build quay.io/keycloak/keycloak-operator:test` would be failed as this issue shows.

@JiyeYu thanks for reporting this. Even though we understand that it's a common practice to use operator-sdk to build new images, we could not find any efficient way to trigger the build with operator-sdk from quay.io, so that's the reason why we use Docker. So to build the operator just run:

```
docker build --no-cache -t ${NAMESPACE}/${PROJECT}:${VERSION} -f build/Dockerfile
```
At the moment this is how it works. I will update the readme to reflect these instructions.

Please feel free to reopen this issue if I didn't answer your question.

**Comment by JiyeYu** [comment]
@abstractj thank you for your answer. Now I understand your intention on that change.
