### ISSUE TITLE
feature request: possiblity to mount files

### ISSUE THREAD

**Issue by 1337andre** [keycloak/keycloak-operator#92]
## Description
We need the possiblity to mount files like keytab from secret.
Furthermore it would be nice to mount themes from sidecar volume or to retrieve via curl/wget from url like init-extensions?

## Expected Behavior
you can mount files from secret

## Actual Behavior
not posible to mount custom secrets

## Environment
* Kubernetes version: v1.15.3

**Comment by abstractj** [comment]
@1337andre thanks for reporting this. I'd appreciate if you join us on the https://groups.google.com/forum/#!forum/keycloak-dev, so we can continue this discussion there.

Our [contributing guidelines](https://github.com/keycloak/keycloak-operator/blob/master/CONTRIBUTING.md) were updated to keep consistency across the Keycloak organization and soon GH issues will be disabled.

For now, I'm closing this, but feel free to drop us an e-mail on the dev mailing list if you have any questions. My apologies for the inconvenience. //cc @slaskawi
