### ISSUE TITLE
Configure ingress controller domain

### ISSUE THREAD

**Issue by psyreactor** [keycloak/keycloak-operator#93]
## Description
It is possible to configure the domain of the ingress controller?.
example: keycloak.test.com.ar

## Expected Behavior
Configure ingress url in keycloak custom resource.

## Actual Behavior
There are no properties to create ingress domain.
Default ingress IP address

## Environment
Kubernetes version: 1.14

Regards

**Comment by slaskawi** [comment]
Thanks for submitting this issue @psyreactor !

Yes, there are no settings for setting up the domain. However, you can modify the Ingress object and set the domain manually. The reconciliation loop won't override your settings.

At the same time, I'd like to ask if you preferred to have an option to set a domain name in the CR or maybe you'd like to be allowed to modify some of the bits in the Ingress manually (as you are today, with the current implementation)?

**Comment by abstractj** [comment]
@psyreactor  thanks for reporting this. I'd appreciate if you join us on the https://groups.google.com/forum/#!forum/keycloak-dev, so we can continue this discussion there.

Our [contributing guidelines](https://github.com/keycloak/keycloak-operator/blob/master/CONTRIBUTING.md) were updated to keep consistency across the Keycloak organization and soon GH issues will be disabled.

For now, I'm closing this, but feel free to drop us an e-mail on the dev mailing list if you have any questions. My apologies for the inconvenience. //cc @slaskawi
