### ISSUE TITLE
Liveness and Readiness fails are killing pod

### ISSUE THREAD

**Issue by hguerrero** [keycloak/keycloak-operator#95]
## Description

Keycloak can't start as it takes longer in some env for the liveness and readiness probes to success
## Expected Behavior

Be able to extend the time for the probes from configuration so keycloak can start when deploying for the first time.
## Actual Behavior

Keycloak is being killed since readiness and liveness probes fail for the time config.
## Environment
* OpenShift or Kubernetes version:

* Project Version/Tag: (E.g release-1.0.1)
Kubernetes 1.16 on Digital Ocean

**Comment by slaskawi** [comment]
Thanks for submitting this ticket @hguerrero 

We already noticed this problem in certain scenarios. However it also requires a bit of a work on the Keycloak Container itself before introducing changes to the Operator. We plan to enhance this in subsequent versions.

If you'd like to subscribe to this issue and be notified about its progress, please subscribe to our tracking JIRA: https://issues.redhat.com/browse/KEYCLOAK-12398

**Comment by abstractj** [comment]
@hguerrero thanks for reporting this. I'd appreciate if you join us on the https://groups.google.com/forum/#!forum/keycloak-dev, so we can continue this discussion there.

Our [contributing guidelines](https://github.com/keycloak/keycloak-operator/blob/master/CONTRIBUTING.md) were updated to keep consistency across the Keycloak organization and soon GH issues will be disabled.

For now, I'm closing this, but feel free to drop us an e-mail on the dev mailing list if you have any questions. My apologies for the inconvenience. //cc @slaskawi
